### ISSUE TITLE
ID3DXBuffer returns null -> crash

### ISSUE THREAD

**Issue by zeromus** [SlimDX/slimdx#505]
OK, you wouldn't believe thus unless you'd seen it with your own two eyes. This is far from the first report I've got of this:
https://github.com/TASVideos/BizHawk/issues/623

in `String^ Utilities::BufferToString( ID3DXBuffer *buffer )` we have GetBufferPointer() returning NULL. Looking around on the web, I can't find ANYONE who tests it for null before printing it.  

Maybe all their error printing routines can handle null pointers? Or maybe they're not trying to get the error string unless the D3DXCompileShader fails?  Anyway, slimdx chokes trying to make a managed string out of it.  I'm changing the code to this and having my guys test it:
```
String^ Utilities::BufferToString( ID3DXBuffer *buffer )
{
	if( buffer != NULL )
	{
		LPVOID ptr = buffer->GetBufferPointer();
		if(!ptr)
			return String::Empty;

		String^ string = gcnew String( reinterpret_cast<const char*>( ptr ) );
		buffer->Release();
		return string;
	}
	else
	{
		return String::Empty;
	}
}
```

I'm using the same OS and driver version they are and I don't have this problem. I'm sure it's something wrong with some people's systems, but I think it's a freak misfortune that it chokes slimdx. Maybe the problem's at the D3DX layer? Anyway, easy to workaround.

**Comment by Promit** [comment]
I'm happy to add the fix, but I admit, I'm surprised that the buffer can be valid without a valid pointer. Why would the compiler return a buffer if there's nothing in it? Just another odd quirk hiding deep in the runtime system, I suppose.

**Comment by AraHaan** [comment]
its not the runtime its you not clearing the buffer when I read your own code.

**Comment by zeromus** [comment]
I would love someone else to chime in here, but I can't make any sense of your reply. What's "your own code"?

**Comment by AraHaan** [comment]
see if you can do a ``buffer->Clear();`` or `` ptr = NULL;`` or ``buffer = NULL;`` after you are done with it.

**Comment by AraHaan** [comment]
oh wait it was fixed already. Why is this not closed then?

**Comment by zeromus** [comment]
I dont know, was it fixed? I just posted a suggested fix here and said I'd have my guys test it, but we havent made a new release since then.

**Comment by AraHaan** [comment]
https://github.com/SlimDX/slimdx/commit/e24f1c2c9cee42faac1f6b940e799a09512d3a4a

**Comment by zeromus** [comment]
oh. well then.
